Repository RightCapitalHQ/phpdoc-parser, pull requests merged in 2024-01, with the labels that each got.

#74 fix(parser): not able to correctly parse quoted array shape and object shape key
  change/@rightcapital-phpdoc-parser-c7976742-fba3-495d-8c41-1bda8d80516f.json
  src/phpdoc-parser/parser/type-parser.ts
Labels: bugfix

#75 chore: cleanup unused `start` command
  package.json
Labels: enhancement

#76 test: replace jest with vitest
  beachball.config.js
  change/@rightcapital-phpdoc-parser-069bc866-49f6-4ce2-ac51-60739be693c7.json
  jest.config.ts
  package.json
  pnpm-lock.yaml
  tests/lexer/__snapshots__/lexer.test.ts.snap
  tests/lexer/lexer.test.ts
  tests/parser/const-expr-node.test.ts
  tests/printer/differ.test.ts
Labels: enhancement, ci
